export const APP_INIT = 'APP_INIT';
export const APP_INIT_ERROR = 'APP_INIT_ERROR';
export const PHONE_SAVE_REQUSET = 'PHONE_SAVE_REQUSET';
export const PHONE_SAVE_SUCCESS = 'PHONE_SAVE_SUCCESS';
export const PHONE_SAVE_FAILED = 'PHONE_SAVE_FAILED';
